---
title: "Thesis"
author: "Brady Pham"
date: 2024-06-13
output: github_document
## 
---


```{r}
library(tidyverse)
library(dplyr)
library(epitools)
library(broom)
library(nnet)
```

```{r}
data <- read.csv("Thesis data.csv")

#Cleaning Education variable
data <- data %>%
  mutate(edu_bl = case_when(
    edu_bl == "8th grade or less" ~ "Less than High School",
    edu_bl == "Some high school, no diploma or GED" ~ "Less than High School",
    edu_bl == "Some college, no degree (including currently in college)" ~ "High school graduate/GED",
    edu_bl == "Some graduate work, no graduate degree" ~ "Greater than High School",
    edu_bl == "Bachelor's degree" ~ "Greater than High School",
    edu_bl == "Bachelor’s degree" ~ "Greater than High School",
    edu_bl == "Associate degree in college" ~ "Greater than High School",
    edu_bl == "Graduate degree (Master’s/Doctoral/Professional degree)" ~ "Greater than High School",
    TRUE ~ edu_bl 
  ))

#Cleaning Race Variable
data <- data %>%
  mutate(race = case_when( 
    race %in% c("American Indian", "Asian/Asian American", "Middle Eastern/North African") ~"Other",
    TRUE ~ race
    ))

#Cleaning Income
data <- data |>
  mutate(income_bl = ifelse(income_bl %in% c("Don't know", "Prefer not to answer"), NA, income_bl)) |>
  mutate(income_bl = case_when(
    income_bl %in% c("No income", "$1 to  $9,999") ~ "Less than $10,000", 
    income_bl %in% c("$10,000 to  $29,999", "$100,000 to  $149,999", "$30,000 to  $49,999",
                     "$50,000 to  $74,999", "$75,000 to  $99,999") ~ "Greater than $10,000",
    TRUE ~ income_bl
  ))

#Cleaning health and status
data <- data %>%
  mutate(health_bl = case_when(
    health_bl == "Excellent" ~ "Good",
    health_bl == "Good" ~ "Good",
    health_bl == "Very Good" ~ "Good",
    health_bl == "Fair" ~ "Fair/Poor",
    health_bl == "Poor" ~ "Fair/Poor",
    TRUE ~ health_bl
  ))

#Cleaning having insurance 
data <- data %>%
  mutate(insurance_bl = case_when(
    insurance_bl %in% c("Yes, for all 6 months", "Yes, for part of the 6 months") ~ "Yes",
    TRUE ~ insurance_bl
      ))

#Cleaning Denied insurance 

data <- data |> 
  mutate(insurance_denied_transcare_bl = ifelse(insurance_denied_transcare_bl %in% c("Don't know", "You have not asked for this"), NA, insurance_denied_transcare_bl)) |>
  mutate(insurance_denied_transcare_bl = case_when(
    insurance_denied_transcare_bl %in% c("Yes, but not within the past 6 months", "Yes, within the past 6 months") ~ "Yes",
    TRUE ~ insurance_denied_transcare_bl
  ))

#Cleaning Healthcare discrimination
data <- data |> 
  mutate(dscrm_hc_bl = case_when(
    dscrm_hc_bl %in% c("All or almost all of the time", "Don't know", "Most of the time", "Sometimes")
    ~ "Yes",
    TRUE ~ dscrm_hc_bl
  ))

#Cleaning Dr denied
data <- data |> 
  mutate(dr_denied_transcare_bl = case_when(
    dr_denied_transcare_bl %in% c("Yes, but not within the past 6 months", "Don't know", "Yes, within the past 6 months")
    ~ "Yes",
    TRUE ~ dr_denied_transcare_bl
  ))




```

```{r}
#Race and education table 
race_education_table <- table(data$race, data$edu_bl)
print(race_education_table)

#Race and education odds ratio and chisquare

odds_ratio_education <- oddsratio(race_education_table)
print(odds_ratio_education)

chi_square_test_education <- chisq.test(race_education_table)
print(chi_square_test_education)

```


```{r}
#Income and race table 
race_income_table <- table(data$race, data$income_bl)
print(race_income_table)

#income and race odds ratio and income
odds_ratio_income <- oddsratio(race_income_table)
print(odds_ratio_income)

chi_square_test_income <- chisq.test(race_income_table)
print(chi_square_test_income)


```



```{r}
#Health status and race table
health_race_table <- table(data$race,data$health_bl)
print(health_race_table)

#Health status and race odds ratio and chi square
odds_ratio_health <- oddsratio(health_race_table)
print(odds_ratio_health)

chi_square_test_health <- chisq.test(health_race_table)
print(chi_square_test_health)

```


```{r}
#Having insurance and race table
insurance_race_table <- table(data$race, data$insurance_bl)
print(insurance_race_table)

#Having insurance and race odds ratio and chi square
odds_ratio_insurance <- oddsratio(insurance_race_table)
print(odds_ratio_insurance)

chi_square_test_insurance <- chisq.test(insurance_race_table)
print(chi_square_test_insurance)


```


```{r}
#Denied insurance and race table 
insurance_denied_table <- table(data$race, data$insurance_denied_transcare_bl)
print(insurance_denied_table)

#Denied insurance and race odds ratio and chi square
odds_ratio_denied <- oddsratio(insurance_denied_table)
print(odds_ratio_denied)

chi_square_test_denied <- chisq.test(insurance_denied_table)
print(chi_square_test_denied)


```

```{r}
#Healthcare discrimination and race table
Mistreatment_healthcare_table <- table(data$race, data$dscrm_hc_bl) 
print(Mistreatment_healthcare_table)

#Healthcare discrimination and race odds ratio and chisquare
odds_ratio_mistreatment <- oddsratio(Mistreatment_healthcare_table)
print(odds_ratio_mistreatment)

chi_square_test_mistreatment <- chisq.test(Mistreatment_healthcare_table)
print(chi_square_test_mistreatment)


```

```{r}
#Dr denied and race table
Dr_denied_table <- table(data$race, data$dr_denied_transcare_bl)
print(Dr_denied_table)

#Dr denied and race odds ratio and chi square 
odds_ratio_dr_denied <- oddsratio(Dr_denied_table)
print(odds_ratio_dr_denied)

chi_square_test_dr_denied <- chisq.test(Dr_denied_table)
print(chi_square_test_dr_denied)

```

```{r}
#Everyday discrimination and race table 
eds_bl_table <- table(data$race, data$eds_bl)
print(eds_bl_table)

#Everyday discriminaiton and race odds ratio and chi square 
odds_ratio_eds_bl <- oddsratio(eds_bl_table)
print(odds_ratio_eds_bl)

chi_square_test_eds <- chisq.test(eds_bl_table)
print(chi_square_test_eds)

```



```{r}
#Bivariate analysis 

#Discrimination in healthcare and everyday discrimination
table(data$dscrm_hc_bl, data$eds_bl)
chisq.test(table(data$dscrm_hc_bl, data$eds_bl))

#Looking it by race
table(data$dscrm_hc_bl, data$eds_bl, data$race)

#Has 0 cell
#Other race low yes


#chisquare test 

results_discrim <- data %>%
  group_by(race) %>%
  summarise(
    chisq_test = list(chisq.test(table(dscrm_hc_bl, eds_bl)))
  )
results_discrim <- results_discrim %>%
  rowwise() %>%
  mutate(
    p_value = chisq_test$p.value,
    statistic = chisq_test$statistic,
    df = chisq_test$parameter
  ) %>%
  select(-chisq_test)

print(results_discrim)

```


```{r}

#insurance denial and everyday discrimination
table(data$insurance_denied_transcare_bl, data$eds_bl)
chisq.test(table(data$insurance_denied_transcare_bl, data$eds_bl))

#Looking it by race
table(data$insurance_denied_transcare_bl, data$eds_bl, data$race)
#Has 0 cell
#Other race no low


#chisquare test 

results_insurance <- data %>%
  group_by(race) %>%
  summarise(
    chisq_test = list(chisq.test(table(insurance_denied_transcare_bl, eds_bl)))
  )
results_insurance <- results_insurance %>%
  rowwise() %>%
  mutate(
    p_value = chisq_test$p.value,
    statistic = chisq_test$statistic,
    df = chisq_test$parameter
  ) %>%
  select(-chisq_test)

print(results_insurance)
```


```{r}
#doctor denial and everyday discrimination
table(data$dr_denied_transcare_bl, data$eds_bl)
chisq.test(table(data$dr_denied_transcare_bl, data$eds_bl))

#Looking it by race
table(data$dr_denied_transcare_bl, data$eds_bl, data$race)
#Has O cell
#Other race yes low 
#Other race yes medium

#chisquare test 

results_doctor <- data %>%
  group_by(race) %>%
  summarise(
    chisq_test = list(chisq.test(table(dr_denied_transcare_bl, eds_bl)))
  )
results_doctor <- results_doctor %>%
  rowwise() %>%
  mutate(
    p_value = chisq_test$p.value,
    statistic = chisq_test$statistic,
    df = chisq_test$parameter
  ) %>%
  select(-chisq_test)

print(results_doctor)
```


```{r}
#Healthcare discrimination, adjusting health status 

results_discrim <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ dscrm_hc_bl + health_bl, data = .)
    tidy(model)
  })

results_discrim <- results_discrim %>%
  filter(grepl("dscrm_hc_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_discrim)

```

```{r}
#Healthcare discrimination, adjusting income

results_discrim <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ dscrm_hc_bl + income_bl, data = .)
    tidy(model)
  })

results_discrim <- results_discrim %>%
  filter(grepl("dscrm_hc_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_discrim)
```

```{r}
#Healthcare discrimination, adjusting education

results_discrim <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ dscrm_hc_bl + edu_bl, data = .)
    tidy(model)
  })

results_discrim <- results_discrim %>%
  filter(grepl("dscrm_hc_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_discrim)


```


```{r}
#insurance denied, adjusting health status

results_insurance <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ insurance_denied_transcare_bl + health_bl, data = .)
    tidy(model)
  })

results_insurance <- results_insurance %>%
  filter(grepl("insurance_denied_transcare_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_insurance)
```


```{r}
#insurance denied, adjusting income

results_insurance <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ insurance_denied_transcare_bl + income_bl, data = .)
    tidy(model)
  })

results_insurance <- results_insurance %>%
  filter(grepl("insurance_denied_transcare_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_insurance)
```

```{r}
#insurance denied, adjusting education

results_insurance <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ insurance_denied_transcare_bl + edu_bl, data = .)
    tidy(model)
  })

results_insurance <- results_insurance %>%
  filter(grepl("insurance_denied_transcare_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_insurance)
```

```{r}
#Doctor denial, adjusting health status
results_doctor <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ dr_denied_transcare_bl + health_bl, data = .)
    tidy(model)
  })

results_doctor <- results_doctor %>%
  filter(grepl("dr_denied_transcare_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_doctor)
```


```{r}
#Doctor denial, adjusting income
results_doctor <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ dr_denied_transcare_bl + income_bl, data = .)
    tidy(model)
  })

results_doctor <- results_doctor %>%
  filter(grepl("dr_denied_transcare_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_doctor)
```

```{r}
#Doctor denial, adjusting education
results_doctor <- data %>%
  group_by(race) %>%
  do({
    model <- multinom(eds_bl ~ dr_denied_transcare_bl + edu_bl, data = .)
    tidy(model)
  })

results_doctor <- results_doctor %>%
  filter(grepl("dr_denied_transcare_bl", term)) %>%
  select(race, term, estimate, std.error, statistic, p.value)

print(results_doctor)
```






